jaffle_shop: # this needs to match the profile in your dbt_project.yml file
  target: dev
  outputs:
    dev:
      type: 'postgres'
      host: 'localhost'
      user: 'postgres'
      password: 'password'
      port: 5433
      dbname: 'dbt_tutorial'
      schema: 'public'
      threads: 1
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections
      #search_path: [optional, override the default postgres search_path]
      #role: [optional, set the role dbt assumes when executing queries]
      #sslmode: [optional, set the sslmode used to connect to the database]
